package com.yext.analytics

/**
 * The action types accepted by the Analytics Events API.
 */
sealed class Action(val value: String) {
    object AddToCart : Action("ADD_TO_CART")
    object AllTabNavigation : Action("ALL_TAB_NAVIGATION")
    object Apply : Action("APPLY")
    object AutoCompleteSelection : Action("AUTO_COMPLETE_SELECTION")
    object BackwardPaginate : Action("BACKWARD_PAGINATE")
    object Book : Action("BOOK")
    object BrandIcon : Action("BRAND_ICON")
    object CaseStart : Action("CASE_START")
    object CaseSubmitted : Action("CASE_SUBMITTED")
    object ChatImpression : Action("CHAT_IMPRESSION")
    object ChatLinkClick : Action("CHAT_LINK_CLICK")
    object ChatResponse : Action("CHAT_RESPONSE")
    object CitationClick : Action("CITATION_CLICK")
    object Collapse : Action("COLLAPSE")
    object CtaClick : Action("CTA_CLICK")
    object DrivingDirections : Action("DRIVING_DIRECTIONS")
    object Event : Action("EVENT")
    object Expand : Action("EXPAND")
    object FeaturedMessage : Action("FEATURED_MESSAGE")
    object FilteringWithinSection : Action("FILTERING_WITHIN_SECTION")
    object ForwardPaginate : Action("FORWARD_PAGINATE")
    object HeaderLinks : Action("HEADER_LINKS")
    object ItemInList : Action("ITEM_IN_LIST")
    object Link : Action("LINK")
    object MapCard : Action("MAP_CARD")
    object MapPin : Action("MAP_PIN")
    object Menu : Action("MENU")
    object Message : Action("MESSAGE")
    object Order : Action("ORDER")
    object PageView : Action("PAGE_VIEW")
    object Paginate : Action("PAGINATE")
    object Post : Action("POST")
    object PresetPrompt : Action("PRESET_PROMPT")
    object Product : Action("PRODUCT")
    object Profile : Action("PROFILE")
    object QuestionFocus : Action("QUESTION_FOCUS")
    object QuestionSubmit : Action("QUESTION_SUBMIT")
    object RemovedFilter : Action("REMOVED_FILTER")
    object Review : Action("REVIEW")
    object ScrollToBottomOfPage : Action("SCROLL_TO_BOTTOM_OF_PAGE")
    object SearchBarImpression : Action("SEARCH_BAR_IMPRESSION")
    object SearchClearButton : Action("SEARCH_CLEAR_BUTTON")
    object TapToCall : Action("TAP_TO_CALL")
    object ThumbsDown : Action("THUMBS_DOWN")
    object ThumbsUp : Action("THUMBS_UP")
    object TicketUrl : Action("TICKET_URL")
    object Title : Action("TITLE")
    object VerticalTabNavigation : Action("VERTICAL_TAB_NAVIGATION")
    object VerticalViewAll : Action("VERTICAL_VIEW_ALL")
    object VoiceStart : Action("VOICE_START")
    object VoiceStop : Action("VOICE_STOP")
    object Website : Action("WEBSITE")
    
    /**
     * Custom action with a C_ prefix
     */
    data class Custom(val customValue: String) : Action("C_$customValue")
}