name: Build Chat assets

on:
  workflow_call:
    inputs:
      build_script:
        required: false
        default: build
        type: string
      region:
        required: false
        default: US
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: VITE_REGION=${{ inputs.region }} npm run ${{ inputs.build_script }}
      - name: Create build-output-${{ inputs.region }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ inputs.region }}
          path: dist/ 
