name: Code Format
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier and ESLint
        run: |
          npm run format
          npm run lint
      - name: Commit and push formatting changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -m "Auto-fix formatting issues with Prettier and ESLint" || echo "No changes to commit"
          git push
