# This workflow will run our tests, generate an lcov code coverage file,
# and send that coverage to Coveralls 

name: Code Coverage

on:
  push:
    branches-ignore: dev/*
  pull_request:

jobs:
  Coveralls:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm ci
    - run: npx jest --coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}