name: GitTools

on: [push]

jobs:
  Gitversion:
    runs-on: ubuntu-latest

    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.10
      with:
        versionSpec: '5.x'
      
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"