name: Playwright Tests
on: [push, pull_request]

env: 
  YEXT_API_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: build package
      run: npm run build
    - name: Run Playwright tests
      run: npx playwright test
