name: Playwright Tests
on: [push, pull_request]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: build main package
      run: npm run build
    - name: Install test site dependencies
      run: npm i --prefix ./test-site
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Build test site
      run: npm run build --prefix ./test-site
    - name: RUn test site
      run: npm run serve --prefix ./test-site
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
