name: Playwright Tests
on: [push, pull_request]

env: 
  YEXT_API_KEY: ${{ secrets.YEXT_API_KEY }}

jobs:
  test-e2e:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci && npm i --prefix ./test-site
    - name: build package
      run: npm run build
    - name: Run Playwright tests
      env:
        # Refer to: https://github.com/microsoft/playwright/issues/6500#issuecomment-1577221956
        HOME: /root
      run: npx playwright test

