# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests
on:
  workflow_call:
    inputs:
      build_script:
        required: false
        type: string
        default: npm run build
      test_script:
        required: false
        type: string
        default: npm test
      working_directory:
        required: false
        type: string
        default: .
      node_matrix:
        required: false
        type: string
        default: '["14.x", "16.x"]'
    secrets:
      NPM_TOKEN:
        required: false
      MAPBOX_API_KEY:
        required: false
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    strategy:
      matrix:
        node-version: ${{ fromJSON(inputs.node_matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}